# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 3
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.cache/wt [current_project]
set_property parent.project_path D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_output_repo d:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/program_memory/test_program.coe
read_vhdl -library xil_defaultlib {
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/decode4_pc_statck.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/decode4alu.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/mux_outputs_from_alu_spm_input_ports.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/imports/new/op_codes.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/ram.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/ram32m_behav.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/sel_of_2nd_op_to_alu_and_port_id.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/sel_of_out_port_value.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/shift_and_rotate_operations.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/spm_with_output_reg.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/two_banks_of_16_gp_reg.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/x12_bit_program_address_generator.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/top.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/arith_and_logic_operations.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/decode4_strobes_enables.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/flags.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/program_counter.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/register_bank_control.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/stack.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/new/state_machine.vhd
  D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/imports/new/zipi8.vhd
}
read_ip -quiet D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/program_memory/program_memory.xci
set_property used_in_implementation false [get_files -all d:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/program_memory/program_memory_ooc.xdc]

read_ip -quiet D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/constrs_1/imports/zcu104-xdc-rdf0438/zcu104_Rev1.0_U1_01302018.xdc
set_property used_in_implementation false [get_files D:/workspace/Vivado_2019.2/zipi8_1ipc/zipi8_1ipc.srcs/constrs_1/imports/zcu104-xdc-rdf0438/zcu104_Rev1.0_U1_01302018.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
